# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT += core gui widgets printsupport
TEMPLATE = app
TARGET = ExampleProject
DESTDIR = ../x64/Release
CONFIG += release
LIBS += -L../x64/Release -lQtPlot
INCLUDEPATH += ../QtPlot
DEPENDPATH += ../QtPlot
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(ExampleProject.pri)
